# Principal Component Analysis (PCA) Implementation from Scratch using Python

#### Best material to read from about PCA:
Basic:<br>
https://www.youtube.com/watch?v=g-Hb26agBFg<br>
Python Implementation:<br>
https://plot.ly/ipython-notebooks/principal-component-analysis/

In [1]:
#Import the data
import pandas as pd
from sklearn.datasets import load_breast_cancer
cancer=load_breast_cancer()
df= pd.DataFrame(cancer['data'],columns=cancer['feature_names'])
Target=cancer['target']

In [2]:
#Overview of data
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension           ...             worst radius  \
0                 0.07871           ...                    25.38   
1                 0.05667           ...                    24.99   
2                 0.05999           ...                    23.57   
3                 0.09744           ...                    14.91   
4                 0.05883           ...                    22.54   

   worst texture  worst perimeter  worst area  worst smoothness  \
0          17.33           184.60      2019.0            0.1622   
1          23.41           158.80      1956.0            0.1238   
2          25.53           152.50      1709.0            0.1444   
3          26.50            98.87       567.7            0.2098   
4          16.67           152.20      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 30 columns]

In [3]:
#Split the data into X and Y matrix
X=df.iloc[:].values
Y=Target

In [4]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

#### Step 1: Standardize the data

In [5]:
from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)
X_std.shape

(569, 30)

#### Step 2: Obtain the Eigen vectors and values using covariance, correlation or SVD matrix

In [6]:
#Eigendecomposition of the covariance matrix after standardizing the data
import numpy as np
mean_x_std=np.mean(X_std, axis=0)
cov=(X_std-mean_x_std).T.dot(X_std-mean_x_std)/(X_std.shape[0]-1)
cov

array([[ 1.00176056e+00,  3.24351929e-01,  9.99612069e-01,
         9.89095475e-01,  1.70881506e-01,  5.07014640e-01,
         6.77955036e-01,  8.23976636e-01,  1.48001350e-01,
        -3.12179472e-01,  6.80285970e-01, -9.74887767e-02,
         6.75358538e-01,  7.37159198e-01, -2.22992026e-01,
         2.06362656e-01,  1.94545531e-01,  3.76831225e-01,
        -1.04504545e-01, -4.27163418e-02,  9.71245907e-01,
         2.97530545e-01,  9.66835698e-01,  9.42739295e-01,
         1.19826732e-01,  4.14190751e-01,  5.27839123e-01,
         7.45524434e-01,  1.64241985e-01,  7.07832563e-03],
       [ 3.24351929e-01,  1.00176056e+00,  3.30113223e-01,
         3.21650988e-01, -2.34296930e-02,  2.37118951e-01,
         3.02950254e-01,  2.93980713e-01,  7.15266864e-02,
        -7.65717560e-02,  2.76354360e-01,  3.87037830e-01,
         2.82169018e-01,  2.60302460e-01,  6.62542133e-03,
         1.92312595e-01,  1.43545353e-01,  1.64139495e-01,
         9.14323671e-03,  5.45533955e-02,  3.53193674e-

Step 3: Obtain Eigenvectors and values

In [7]:
eigen_vals, eigen_vec = np.linalg.eig(cov)
print(eigen_vals)
eigen_vec

[1.33049908e+01 5.70137460e+00 2.82291016e+00 1.98412752e+00
 1.65163324e+00 1.20948224e+00 6.76408882e-01 4.77456255e-01
 4.17628782e-01 3.51310875e-01 2.94433153e-01 2.61621161e-01
 2.41782421e-01 1.57286149e-01 9.43006956e-02 8.00034045e-02
 5.95036135e-02 5.27114222e-02 4.95647002e-02 1.33279057e-04
 7.50121413e-04 1.59213600e-03 6.91261258e-03 8.19203712e-03
 1.55085271e-02 1.80867940e-02 2.43836914e-02 2.74877113e-02
 3.12142606e-02 3.00256631e-02]


array([[ 2.18902444e-01, -2.33857132e-01, -8.53124284e-03,
         4.14089623e-02, -3.77863538e-02,  1.87407904e-02,
         1.24088340e-01,  7.45229622e-03, -2.23109764e-01,
         9.54864432e-02,  4.14714866e-02,  5.10674568e-02,
         1.19672116e-02, -5.95061348e-02,  5.11187749e-02,
        -1.50583883e-01,  2.02924255e-01,  1.46712338e-01,
        -2.25384659e-01, -7.02414091e-01,  2.11460455e-01,
        -2.11194013e-01, -1.31526670e-01,  1.29476396e-01,
         1.92264989e-02, -1.82579441e-01,  9.85526942e-02,
        -7.29289034e-02, -4.96986642e-02,  6.85700057e-02],
       [ 1.03724578e-01, -5.97060883e-02,  6.45499033e-02,
        -6.03050001e-01,  4.94688505e-02, -3.21788366e-02,
        -1.13995382e-02, -1.30674825e-01,  1.12699390e-01,
         2.40934066e-01, -3.02243402e-01,  2.54896423e-01,
         2.03461333e-01,  2.15600995e-02,  1.07922421e-01,
        -1.57841960e-01, -3.87061187e-02, -4.11029851e-02,
        -2.97886446e-02, -2.73661018e-04, -1.05339342e-

The eigendecomposition of the covariance matrix (if the input data was standardized) yields the same results as a eigendecomposition on the correlation matrix, since the correlation matrix can be understood as the normalized covariance matrix. Thus, all three approaches below yield the same eigenvectors and eigenvalue pairs:

1. Eigendecomposition of the covariance matrix after standardizing the data.
2. Eigendecomposition of the correlation matrix.
3. Eigendecomposition of the correlation matrix after standardizing the data.

In [8]:
#Eigendecomposition of the correlation matrix
eigen_vals, eigen_vec =np.linalg.eig(np.corrcoef(X.T))
print(eigen_vals)
eigen_vec

[1.32816077e+01 5.69135461e+00 2.81794898e+00 1.98064047e+00
 1.64873055e+00 1.20735661e+00 6.75220114e-01 4.76617140e-01
 4.16894812e-01 3.50693457e-01 2.93915696e-01 2.61161370e-01
 2.41357496e-01 1.57009724e-01 9.41349650e-02 7.98628010e-02
 5.93990378e-02 5.26187835e-02 4.94775918e-02 1.33044823e-04
 7.48803097e-04 1.58933787e-03 6.90046388e-03 8.17763986e-03
 1.54812714e-02 1.80550070e-02 2.43408378e-02 2.74394025e-02
 3.11594025e-02 2.99728939e-02]


array([[ 2.18902444e-01, -2.33857132e-01, -8.53124284e-03,
         4.14089623e-02, -3.77863538e-02,  1.87407904e-02,
         1.24088340e-01,  7.45229622e-03, -2.23109764e-01,
         9.54864432e-02,  4.14714866e-02,  5.10674568e-02,
         1.19672116e-02, -5.95061348e-02, -5.11187749e-02,
         1.50583883e-01, -2.02924255e-01, -1.46712338e-01,
        -2.25384659e-01, -7.02414091e-01,  2.11460455e-01,
        -2.11194013e-01, -1.31526670e-01,  1.29476396e-01,
         1.92264989e-02, -1.82579441e-01,  9.85526942e-02,
        -7.29289034e-02, -4.96986642e-02,  6.85700057e-02],
       [ 1.03724578e-01, -5.97060883e-02,  6.45499033e-02,
        -6.03050001e-01,  4.94688505e-02, -3.21788366e-02,
        -1.13995382e-02, -1.30674825e-01,  1.12699390e-01,
         2.40934066e-01, -3.02243402e-01,  2.54896423e-01,
         2.03461333e-01,  2.15600995e-02, -1.07922421e-01,
         1.57841960e-01,  3.87061187e-02,  4.11029851e-02,
        -2.97886446e-02, -2.73661018e-04, -1.05339342e-

In [9]:
#Eigendecomposition of the correlation matrix after standardizing the data
eigen_vals, eigen_vec = np.linalg.eig(np.corrcoef(X_std.T))
print(eigen_vals)
print(eigen_vec)

[1.32816077e+01 5.69135461e+00 2.81794898e+00 1.98064047e+00
 1.64873055e+00 1.20735661e+00 6.75220114e-01 4.76617140e-01
 4.16894812e-01 3.50693457e-01 2.93915696e-01 2.61161370e-01
 2.41357496e-01 1.57009724e-01 9.41349650e-02 7.98628010e-02
 5.93990378e-02 5.26187835e-02 4.94775918e-02 1.33044823e-04
 7.48803097e-04 1.58933787e-03 6.90046388e-03 8.17763986e-03
 1.54812714e-02 1.80550070e-02 2.43408378e-02 2.74394025e-02
 3.11594025e-02 2.99728939e-02]
[[ 2.18902444e-01 -2.33857132e-01 -8.53124284e-03  4.14089623e-02
  -3.77863538e-02  1.87407904e-02  1.24088340e-01  7.45229622e-03
  -2.23109764e-01  9.54864432e-02  4.14714866e-02  5.10674568e-02
   1.19672116e-02 -5.95061348e-02  5.11187749e-02 -1.50583883e-01
   2.02924255e-01  1.46712338e-01  2.25384659e-01  7.02414091e-01
  -2.11460455e-01  2.11194013e-01  1.31526670e-01 -1.29476396e-01
  -1.92264989e-02  1.82579441e-01  9.85526942e-02 -7.29289034e-02
  -4.96986642e-02  6.85700057e-02]
 [ 1.03724578e-01 -5.97060883e-02  6.4549903

While the eigendecomposition of the covariance or correlation matrix may be more intuitiuve, most PCA implementations perform a Singular Vector Decomposition (SVD) to improve the computational efficiency.

In [10]:
u,s,v =np.linalg.svd(X_std.T)
print(u)

[[-2.18902444e-01  2.33857132e-01  8.53124284e-03 -4.14089623e-02
   3.77863538e-02 -1.87407904e-02  1.24088340e-01 -7.45229622e-03
   2.23109764e-01 -9.54864432e-02  4.14714866e-02 -5.10674568e-02
  -1.19672116e-02  5.95061348e-02  5.11187749e-02  1.50583883e-01
  -2.02924255e-01 -1.46712338e-01  2.25384659e-01  4.96986642e-02
   6.85700057e-02  7.29289034e-02  9.85526942e-02  1.82579441e-01
  -1.92264989e-02 -1.29476396e-01 -1.31526670e-01 -2.11194013e-01
  -2.11460455e-01 -7.02414091e-01]
 [-1.03724578e-01  5.97060883e-02 -6.45499033e-02  6.03050001e-01
  -4.94688505e-02  3.21788366e-02 -1.13995382e-02  1.30674825e-01
  -1.12699390e-01 -2.40934066e-01 -3.02243402e-01 -2.54896423e-01
  -2.03461333e-01 -2.15600995e-02  1.07922421e-01  1.57841960e-01
   3.87061187e-02  4.11029851e-02  2.97886446e-02  2.44134993e-01
  -4.48369467e-01  9.48006326e-02  5.54997454e-04 -9.87867898e-02
   8.47459309e-02 -2.45566636e-02 -1.73573093e-02  6.58114593e-05
   1.05339342e-02 -2.73661018e-04]
 [-2.2

#### Step 3: Sort eigenvalues in descending order and choose the k eigenvectors that correspond to the k largest eigenvalues where k is the number of dimensions of the new feature subspace (k≤d).

In [11]:
eigen_vec[1,:]

array([ 1.03724578e-01, -5.97060883e-02,  6.45499033e-02, -6.03050001e-01,
        4.94688505e-02, -3.21788366e-02, -1.13995382e-02, -1.30674825e-01,
        1.12699390e-01,  2.40934066e-01, -3.02243402e-01,  2.54896423e-01,
        2.03461333e-01,  2.15600995e-02,  1.07922421e-01, -1.57841960e-01,
       -3.87061187e-02, -4.11029851e-02,  2.97886446e-02,  2.73661018e-04,
        1.05339342e-02, -6.58114593e-05,  1.73573093e-02, -2.45566636e-02,
        8.47459309e-02, -9.87867898e-02,  5.54997454e-04, -9.48006326e-02,
       -2.44134993e-01, -4.48369467e-01])

In [12]:
eigen_vals[0]

13.28160768225791

In [13]:
eig_pairs=[(np.abs(eigen_vals[i]), eigen_vec[:,i]) for i in range(len(eigen_vals))]

In [14]:
eig_pairs

[(13.28160768225791,
  array([0.21890244, 0.10372458, 0.22753729, 0.22099499, 0.14258969,
         0.23928535, 0.25840048, 0.26085376, 0.13816696, 0.06436335,
         0.20597878, 0.01742803, 0.21132592, 0.20286964, 0.01453145,
         0.17039345, 0.15358979, 0.1834174 , 0.04249842, 0.10256832,
         0.22799663, 0.10446933, 0.23663968, 0.22487053, 0.12795256,
         0.21009588, 0.22876753, 0.25088597, 0.12290456, 0.13178394])),
 (5.691354613209922,
  array([-0.23385713, -0.05970609, -0.21518136, -0.23107671,  0.18611302,
          0.15189161,  0.06016536, -0.0347675 ,  0.19034877,  0.36657547,
         -0.10555215,  0.08997968, -0.08945723, -0.15229263,  0.20443045,
          0.2327159 ,  0.19720728,  0.13032156,  0.183848  ,  0.28009203,
         -0.21986638, -0.0454673 , -0.19987843, -0.21935186,  0.17230435,
          0.14359317,  0.09796411, -0.00825724,  0.14188335,  0.27533947])),
 (2.817948977229417,
  array([-0.00853124,  0.0645499 , -0.00931422,  0.02869953, -0.1042919 ,

In [15]:
eig_pairs.sort(reverse=True)

In [16]:
for i in range(len(eigen_vals)):
    print(eig_pairs[i][0])

13.28160768225791
5.691354613209922
2.817948977229417
1.9806404746410418
1.6487305477038812
1.2073566119650037
0.6752201138947511
0.4766171400063981
0.416894812367734
0.3506934568239441
0.2939156962794052
0.26116137022136515
0.2413574961590198
0.15700972364779067
0.09413496502882196
0.07986280095456973
0.05939903775972833
0.05261878350679114
0.04947759177675467
0.031159402450161244
0.02997289391100762
0.02743940253163026
0.02434083776697307
0.018055007000150072
0.015481271374955809
0.00817763986432464
0.006900463875178923
0.0015893378711425113
0.0007488030974064989
0.000133044822820632


After sorting the eigenpairs, the next question is "how many principal components are we going to choose for our new feature subspace?" A useful measure is the so-called "explained variance," which can be calculated from the eigenvalues. The explained variance tells us how much information (variance) can be attributed to each of the principal components.

In [17]:
tot=sum(eigen_vals)
tot

29.999999999999996

In [18]:
exp_var=[eig_pairs[i][0]/tot*100 for i in range(len(eigen_vals))]
exp_var

[44.27202560752637,
 18.97118204403308,
 9.39316325743139,
 6.60213491547014,
 5.495768492346271,
 4.024522039883346,
 2.250733712982504,
 1.5887238000213273,
 1.3896493745591134,
 1.1689781894131472,
 0.9797189875980175,
 0.870537900737884,
 0.8045249871967327,
 0.5233657454926356,
 0.3137832167627399,
 0.26620933651523243,
 0.19799679253242777,
 0.17539594502263714,
 0.16492530592251559,
 0.10386467483387084,
 0.0999096463700254,
 0.09146467510543421,
 0.08113612588991023,
 0.06018335666716692,
 0.05160423791651937,
 0.0272587995477488,
 0.023001546250596413,
 0.005297792903808372,
 0.00249601032468833,
 0.00044348274273544]

In [19]:
cumm_exp_var=np.cumsum(exp_var)
cumm_exp_var

array([ 44.27202561,  63.24320765,  72.63637091,  79.23850582,
        84.73427432,  88.75879636,  91.00953007,  92.59825387,
        93.98790324,  95.15688143,  96.13660042,  97.00713832,
        97.81166331,  98.33502905,  98.64881227,  98.91502161,
        99.1130184 ,  99.28841435,  99.45333965,  99.55720433,
        99.65711397,  99.74857865,  99.82971477,  99.88989813,
        99.94150237,  99.96876117,  99.99176271,  99.99706051,
        99.99955652, 100.        ])

The first ten Principal components explain for 95% of the variance, thus we can safely remove the rest 20 of them.

#### Step 4: Construct the projection matrix W from the selected k eigenvectors.

In [20]:
eigen_vec

array([[ 2.18902444e-01, -2.33857132e-01, -8.53124284e-03,
         4.14089623e-02, -3.77863538e-02,  1.87407904e-02,
         1.24088340e-01,  7.45229622e-03, -2.23109764e-01,
         9.54864432e-02,  4.14714866e-02,  5.10674568e-02,
         1.19672116e-02, -5.95061348e-02,  5.11187749e-02,
        -1.50583883e-01,  2.02924255e-01,  1.46712338e-01,
         2.25384659e-01,  7.02414091e-01, -2.11460455e-01,
         2.11194013e-01,  1.31526670e-01, -1.29476396e-01,
        -1.92264989e-02,  1.82579441e-01,  9.85526942e-02,
        -7.29289034e-02, -4.96986642e-02,  6.85700057e-02],
       [ 1.03724578e-01, -5.97060883e-02,  6.45499033e-02,
        -6.03050001e-01,  4.94688505e-02, -3.21788366e-02,
        -1.13995382e-02, -1.30674825e-01,  1.12699390e-01,
         2.40934066e-01, -3.02243402e-01,  2.54896423e-01,
         2.03461333e-01,  2.15600995e-02,  1.07922421e-01,
        -1.57841960e-01, -3.87061187e-02, -4.11029851e-02,
         2.97886446e-02,  2.73661018e-04,  1.05339342e-

In [21]:
matrix_w=eigen_vec[:,:10]

#### Step 5: Transform the original dataset X via W to obtain a 10-dimensional feature subspace Y.

In [22]:
Y_tra=X_std.dot(matrix_w)

In [25]:
Y_df=pd.DataFrame(Y_tra,Y)
Y_df.reset_index(inplace=True)
Y_df.columns=['Target','PC0','PC1','PC2','PC3','PC4','PC5','PC6','PC7','PC8','PC9']
Y_df.head(20)

Target       PC0        PC1       PC2       PC3       PC4       PC5  \
0        0  9.192837   1.948583 -1.123166  3.633731  1.195110  1.411424   
1        0  2.387802  -3.768172 -0.529293  1.118264 -0.621775  0.028656   
2        0  5.733896  -1.075174 -0.551748  0.912083  0.177086  0.541452   
3        0  7.122953  10.275589 -3.232790  0.152547  2.960878  3.053422   
4        0  3.935302  -1.948072  1.389767  2.940639 -0.546747 -1.226495   
5        0  2.380247   3.949929 -2.934877  0.941037  1.056042 -0.451039   
6        0  2.238883  -2.690031 -1.639913  0.149340 -0.040360 -0.128948   
7        0  2.143299   2.340244 -0.871947 -0.127043  1.427437 -1.257039   
8        0  3.174924   3.391813 -3.119986 -0.601297  1.522290  0.559545   
9        0  6.351747   7.727174 -4.341916 -3.375202 -1.710263 -0.723909   
10       0 -0.810414  -2.659275 -0.488830 -1.672567 -0.275812  0.127332   
11       0  2.651100   0.066568 -1.526455  0.051262 -0.331951  0.764867   
12       0  8.185034   2.700976  5.730231 -1.112257 -1.043470  2.594571   
13       0  0.342126  -0.968279  1.717172 -0.595003 -0.468011  1.007660   
14       0  4.342379   4.861083 -2.816116 -1.454557 -1.290063 -0.349716   
15       0  4.075656   2.977061 -3.125274 -2.458071  0.408342  0.495778   
16       0  0.230055  -1.564758 -0.802519 -0.650583  0.494711 -0.762191   
17       0  4.418011   1.418670 -2.270319 -0.186272  1.423861 -0.752489   
18       0  4.948704  -4.114334 -0.314749 -0.088207  0.056715 -1.137689   
19       1 -1.237063  -0.188215 -0.593283  1.596346  0.442154 -0.048637   

         PC6       PC7       PC8       PC9  
0  -2.159370  0.398407 -0.157118 -0.877402  
1  -0.013358 -0.240988 -0.711905  1.106995  
2   0.668166 -0.097374  0.024066  0.454275  
3  -1.429911 -1.059565 -1.405440 -1.116975  
4   0.936213 -0.636376 -0.263805  0.377704  
5  -0.490445  0.165444 -0.133473 -0.530431  
6   0.301567 -0.083698 -0.080025  0.219143  
7  -0.974100  0.653338  0.248184  1.000586  
8   0.215104  0.687341  0.511924  0.029187  
9  -2.519840 -0.365149 -0.717397 -1.165631  
10 -0.625012 -0.165750 -0.301381  0.376235  
11 -0.666092 -0.619545 -0.400941 -0.331069  
12 -0.941497  3.321784 -0.747788  0.395946  
13  1.799081 -1.106657  0.267625  0.439582  
14 -0.742880  0.280926 -0.675104 -0.115657  
15 -0.915057 -0.302524  0.456940  0.447157  
16  0.086847 -0.029509  0.503226 -0.499672  
17 -0.441985  0.413770  0.018673  0.356630  
18  0.251283 -0.742152  0.410447 -0.571327  
19  1.201687 -0.403626  0.405300  0.005926